import Foundation

struct Quote {
    let text: String
    let author: String
}

class QuoteProvider {
    private static let quotes: [Quote] = [
        Quote(text: "The secret of getting ahead is getting started.", author: "Mark Twain"),
        Quote(text: "The best way to predict the future is to create it.", author: "Peter Drucker"),
        Quote(text: "Well done is better than well said.", author: "Benjamin Franklin"),
        Quote(text: "A journey of a thousand miles begins with a single step.", author: "Lao Tzu"),
        Quote(text: "Little by little, one travels far.", author: "J.R.R. Tolkien"),
        Quote(text: "No one can whistle a symphony. It takes a whole orchestra to play it.", author: "H.E. Luccock"),
        Quote(text: "A book is like a garden carried in the pocket.", author: "Chinese Proverb"),
        Quote(text: "If you want to go fast, go alone. If you want to go far, go together.", author: "African Proverb"),
        Quote(text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb"),
        Quote(text: "Courage is not the absence of fear, but the triumph over it.", author: "Nelson Mandela"),
        Quote(text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill"),
        Quote(text: "The only way to do great work is to love what you do.", author: "Steve Jobs"),
        Quote(text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson"),
        Quote(text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt"),
        Quote(text: "It always seems impossible until it's done.", author: "Nelson Mandela"),
        Quote(text: "You reap what you sow.", author: "Indian Proverb"),
        Quote(text: "A single tree does not make a forest.", author: "Indian Proverb"),
        Quote(text: "Wisdom is wealth.", author: "Swahili Proverb"),
        Quote(text: "A diamond with a flaw is worth more than a pebble without imperfections.", author: "Indian Proverb"),
        Quote(text: "A man is not honest simply because he never had a chance to steal.", author: "Indian Proverb"),
        Quote(text: "Knowledge is like a garden; if it is not cultivated, it cannot be harvested.", author: "Indian Proverb"),
        Quote(text: "The mind is like water. When it's turbulent, it's difficult to see. When it's calm, everything becomes clear.", author: "Indian Proverb"),
        Quote(text: "As you think, so you become.", author: "Indian Proverb"),
        Quote(text: "The greatest meditation is a mind that lets go.", author: "Indian Proverb"),
        Quote(text: "Happiness is not something ready-made. It comes from your own actions.", author: "Dalai Lama"),
        Quote(text: "Peace comes from within. Do not seek it without.", author: "Buddha"),
        Quote(text: "Three things cannot be long hidden: the sun, the moon, and the truth.", author: "Buddha"),
        Quote(text: "Health is the greatest gift, contentment the greatest wealth, faithfulness the best relationship.", author: "Buddha"),
        Quote(text: "The way is not in the sky. The way is in the heart.", author: "Buddha"),
        Quote(text: "Just as a candle cannot burn without fire, men cannot live without a spiritual life.", author: "Buddha"),
        Quote(text: "Your work is to discover your world and then with all your heart give yourself to it.", author: "Buddha"),
        Quote(text: "The mind is everything. What you think you become.", author: "Buddha"),
        Quote(text: "To keep the body in good health is a duty... otherwise we shall not be able to keep our mind strong and clear.", author: "Buddha"),
        Quote(text: "Thousands of candles can be lit from a single candle, and the life of the candle will not be shortened. Happiness never decreases by being shared.", author: "Buddha"),
        Quote(text: "The two most important days in your life are the day you are born and the day you find out why.", author: "Mark Twain"),
        Quote(text: "To live is the rarest thing in the world. Most people exist, that is all.", author: "Oscar Wilde"),
        Quote(text: "When you want to succeed as bad as you want to breathe, then you'll be successful.", author: "Eric Thomas"),
        Quote(text: "Hard work beats talent when talent doesn't work hard.", author: "Tim Notke"),
        Quote(text: "A man can be as great as he wants to be. If you believe in yourself and have the courage, the determination, the dedication, the competitive drive and if you are willing to sacrifice the little things in life and pay the price for the things that are worthwhile, it can be done.", author: "Vince Lombardi"),
        Quote(text: "Every great story on the planet happened when someone decided not to give up, but kept going no matter what.", author: "Spryte Loriano"),
        Quote(text: "Don't stop when you're tired. STOP when you are DONE.", author: "Unknown"),
        Quote(text: "Failure will never overtake me if my determination to succeed is strong enough.", author: "Og Mandino"),
        Quote(text: "Success… seems to be connected with action. Successful people keep moving. They make mistakes, but they don't quit.", author: "Conrad Hilton"),
        Quote(text: "Aim for the moon. If you miss, you may hit a star.", author: "W. Clement Stone"),
        Quote(text: "Action is the foundational key to all success.", author: "Pablo Picasso"),
        Quote(text: "The ones who are crazy enough to think they can change the world, are the ones who do.", author: "Unknown"),
        Quote(text: "Successful people do what unsuccessful people are not willing to do. Don't wish it were easier, wish you were better.", author: "Jim Rohn"),
        Quote(text: "The question isn't who is going to let me; it's who is going to stop me.", author: "Ayn Rand"),
        Quote(text: "It does not matter how slowly you go, so long as you do not stop.", author: "Confucius"),
        Quote(text: "Little minds are tamed and subdued by misfortune; but great minds rise above it.", author: "Washington Irving"),
        Quote(text: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson"),
        Quote(text: "Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do, so throw off the bowlines, sail away from safe harbor, catch the trade winds in your sails. Explore, Dream, Discover.", author: "Mark Twain"),
        Quote(text: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar"),
        Quote(text: "Nothing is impossible, the word itself says 'I'm possible'!", author: "Audrey Hepburn"),
        Quote(text: "Life begins at the end of your comfort zone.", author: "Neale Donald Walsh"),
        Quote(text: "The will to win, the desire to succeed, the urge to reach your full potential… these are the keys that will unlock the door to personal excellence.", author: "Confucius"),
        Quote(text: "Things work out best for those who make the best of how things work out.", author: "John Wooden"),
        Quote(text: "Perfection is not attainable, but if we chase perfection we can catch excellence.", author: "Vince Lombardi"),
        Quote(text: "Give me a stock clerk with a goal, and I will give you a man who will make history. Give me a man without a goal, and I will give you a stock clerk.", author: "J.C. Penny"),
        Quote(text: "Nothing in the world is more common than unsuccessful people with talent.", author: "Unknown"),
        Quote(text: "Most of the important things in the world have been accomplished by people who have kept on trying when there seemed to be no help at all.", author: "Dale Carnegie"),
        Quote(text: "Expect problems and eat them for breakfast.", author: "Alfred A. Montapert"),
        Quote(text: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill"),
        Quote(text: "Opportunities don't happen, you create them.", author: "Chris Grosser"),
        Quote(text: "I do not have superior intelligence or faultless looks. I do not captivate a room or run a mile under six minutes. I only succeeded because I was still working after everyone else went to sleep.", author: "Greg Evans"),
        Quote(text: "The greatest pleasure in life is doing what people say you cannot do.", author: "Walter Bagehot"),
        Quote(text: "Remember that not getting what you want is sometimes a wonderful stroke of luck.", author: "Dalai Lama"),
        Quote(text: "The whole secret of a successful life is to find out what is one's destiny to do, and then do it.", author: "Henry Ford"),
        Quote(text: "All our dreams can come true if we have the courage to pursue them.", author: "Walt Disney"),
        Quote(text: "There are two types of people who will tell you that you cannot make a difference in this world: those who are afraid to try and those who are afraid you will succeed.", author: "Ray Goforth"),
        Quote(text: "What's the point of being alive if you don't at least try to do something remarkable.", author: "Unknown"),
        Quote(text: "Our deepest fear is not that we are inadequate. Our deepest fear is that we are powerful beyond measure. It is our light, not our darkness that most frightens us. We ask ourselves, Who am I to be brilliant, gorgeous, talented, fabulous? Actually, who are you not to be? You are a child of God. Your playing small does not serve the world. There is nothing enlightened about shrinking so that other people won't feel insecure around you. We are all meant to shine, as children do.", author: "Marianne Williamson"),
        Quote(text: "I have not failed. I've just found 10,000 ways that won't work.", author: "Thomas A. Edison"),
        Quote(text: "How does one become a butterfly? You must want to fly so much that you are willing to give up being a caterpillar.", author: "Trina Paulus"),
        Quote(text: "Take up one idea. Make that one idea your life—think of it, dream of it, live on that idea. Let the brain, muscles, nerves, every part of your body, be full of that idea, and just leave every other idea alone. This is the way to success.", author: "Swami Vivekananda"),
        Quote(text: "I can't change the direction of the wind, but I can adjust my sails to always reach my destination.", author: "Jimmy Dean"),
        Quote(text: "Failure is the opportunity to begin again more intelligently.", author: "Henry Ford"),
        Quote(text: "There will be obstacles. There will be doubters. There will be mistakes. But with hard work, there are no limits.", author: "Michael Phelps"),
        Quote(text: "Nothing great will ever be achieved without great men, and men are great only if they are determined to be so. For glory gives herself only to those who have always dreamed of her.", author: "Charles De Gaulle"),
        Quote(text: "You got a dream, you gotta protect it. People can't do something themselves, they wanna tell you, you can't do it. If you want something, go get it. Period.", author: "Will Smith"),
        Quote(text: "The successful warrior is the average man, with laser-like focus.", author: "Bruce Lee"),
        Quote(text: "Motivation is a fire from within. If someone else tries to light that fire under you, chances are it will burn very briefly.", author: "Stephen R. Covey"),
        Quote(text: "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.", author: "Thomas A. Edison"),
        Quote(text: "Too many of us are not living our dreams because we are living our fears.", author: "Les Brown"),
        Quote(text: "Security is mostly a superstition. It does not exist in nature, nor do the children of men as a whole experience it. Avoiding danger is no safer in the long run than outright exposure. Life is either a daring adventure, or nothing.", author: "Helen Keller"),
        Quote(text: "Be miserable. Or motivate yourself. Whatever has to be done, it's always your choice.", author: "Wayne Dyer"),
        Quote(text: "Nothing great ever came that easy.", author: "Kresley Cole"),
        Quote(text: "Our greatest fear should not be of failure but of succeeding at things in life that don't really matter.", author: "Francis Chan"),
        Quote(text: "A successful man is one who can lay a firm foundation with the bricks others have thrown at him.", author: "David Brinkley"),
        Quote(text: "The greatest achievement was at first, and for a time, but a dream.", author: "Napoleon Hill"),
        Quote(text: "Good things come to people who wait, but better things come to those who go out and get them.", author: "Unknown"),
        Quote(text: "Great things come to those who don't wait.", author: "Unknown"),
        Quote(text: "People who succeed have momentum. The more they succeed, the more they want to succeed, and the more they find a way to succeed. Similarly, when someone is failing, the tendency is to get on a downward spiral that can even become a self-fulfilling prophecy.", author: "Tony Robbins"),
        Quote(text: "When I was 5 years old, my mother always told me that happiness was the key to life. When I went to school, they asked me what I wanted to be when I grew up. I wrote down \"happy\". They told me I didn't understand the assignment, and I told them they didn't understand life.", author: "John Lennon"),
        Quote(text: "Ones best success comes after their greatest disappointments.", author: "Henry Ward Beecher"),
        Quote(text: "The fishing is best where the fewest go, and the collective insecurity of the world makes it easy for people to hit home runs while everyone else is aiming for base hits. There is just less competition for bigger goals. If you are insecure, guess what? The rest of the world is, too. Do not overestimate the competition and underestimate yourself. You are better than you think.", author: "Timothy Ferris"),
        Quote(text: "It's not about time, it's about choices. How are you spending your choices?", author: "Beverly Abamo"),
        Quote(text: "You will succeed because most people are lazy.", author: "Unknown"),
        Quote(text: "The starting point of all achievement is desire.", author: "Napoleon Hill"),
        Quote(text: "If you want to achieve greatness stop asking for permission.", author: "Unknown"),
        Quote(text: "I find that when you have a real interest in life and a curious life, that sleep is not the most important thing.", author: "Martha Stewart"),
        Quote(text: "There are no great men. Just great challenges which ordinary men, out of necessity, are forced by circumstance to meet.", author: "Admiral William Frederick Halsey Jr."),
        Quote(text: "The only place where success comes before work is in the dictionary.", author: "Vidal Sassoon"),
        Quote(text: "Some people develop a wish bone where their back bone should be.", author: "Unknown"),
        Quote(text: "All progress takes place outside the comfort zone.", author: "Michael John Bobak"),
        Quote(text: "No matter how hard the past is, you can always begin again.", author: "Jack Kornfield"),
        Quote(text: "Infuse your life with action. Don't wait for it to happen. Make it happen. Make your own future. Make your own hope. Make your own love. And whatever your beliefs, honor your creator, not by passively waiting for grace to come down from upon high, but by doing what you can to make grace happen… yourself, right now, right down here on Earth.", author: "Bradley Whitford"),
        Quote(text: "You can never cross the ocean unless you have the courage to lose sight of the shore.", author: "Christopher Columbus"),
        Quote(text: "If you are not willing to risk the usual, you will have to settle for the ordinary.", author: "Jim Rohn"),
        Quote(text: "There are two primary choices in life; to accept conditions as they exist, or to accept the responsibility for changing them.", author: "Dennis Waitely"),
        Quote(text: "More often than not, successful entrepreneurs are givers and not takers of positive energy.", author: "Olaf Isachsen"),
        Quote(text: "Act as if what you do makes a difference. It does.", author: "William James"),
        Quote(text: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett"),
        Quote(text: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Zig Ziglar"),
        Quote(text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt"),
        Quote(text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis"),
        Quote(text: "Try not to become a man of success, but rather try to become a man of value.", author: "Albert Einstein"),
        Quote(text: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt"),
        Quote(text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius"),
        Quote(text: "Everything you've ever wanted is on the other side of fear.", author: "George Addair"),
        Quote(text: "Opportunities don't happen. You create them.", author: "Chris Grosser"),
        Quote(text: "Dream big and dare to fail.", author: "Norman Vaughan"),
        Quote(text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky"),
        Quote(text: "The harder you work, the greater you'll feel when you achieve it.", author: "Unknown"),
        Quote(text: "Push yourself, because no one else is going to do it for you.", author: "Unknown"),
        Quote(text: "Great things never come from comfort zones.", author: "Unknown"),
        Quote(text: "Dream it. Wish it. Do it.", author: "Unknown"),
        Quote(text: "Success doesn't just find you. You have to go out and get it.", author: "Unknown"),
        Quote(text: "The harder you work, the luckier you get.", author: "Gary Player"),
        Quote(text: "Don't stop when you're tired. Stop when you're done.", author: "Marilyn Monroe"),
        Quote(text: "Wake up with determination. Go to bed with satisfaction.", author: "Unknown"),
        Quote(text: "Do something today that your future self will thank you for.", author: "Sean Patrick Flanery"),
        Quote(text: "Little things make big days.", author: "Isabel Marant"),
        Quote(text: "It's going to be hard, but hard does not mean impossible.", author: "Unknown"),
        Quote(text: "Don't wait for opportunity. Create it.", author: "George Bernard Shaw"),
        Quote(text: "Sometimes we're tested not to show our weaknesses, but to discover our strengths.", author: "Unknown"),
        Quote(text: "The key to success is to focus on goals, not obstacles.", author: "Unknown"),
        Quote(text: "Dream bigger. Do bigger.", author: "Unknown"),
        Quote(text: "Don't limit your challenges. Challenge your limits.", author: "Jerry Dunn"),
        Quote(text: "Doubt kills more dreams than failure ever will.", author: "Suzy Kassem"),
        Quote(text: "Success is what happens after you have survived all your mistakes.", author: "Anora Lee"),
        Quote(text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney"),
        Quote(text: "Don't be afraid to give up the good to go for the great.", author: "John D. Rockefeller"),
        Quote(text: "If you are not willing to risk the usual, you will have to settle for the ordinary.", author: "Jim Rohn"),
        Quote(text: "Success is not in what you have, but who you are.", author: "Bo Bennett"),
        Quote(text: "The road to success and the road to failure are almost exactly the same.", author: "Colin R. Davis"),
        Quote(text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau"),
        Quote(text: "Don't be distracted by criticism. Remember—the only taste of success some people get is to take a bite out of you.", author: "Zig Ziglar"),
        Quote(text: "There are no secrets to success. It is the result of preparation, hard work, and learning from failure.", author: "Colin Powell"),
        Quote(text: "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.", author: "Albert Schweitzer"),
        Quote(text: "Success isn't just about what you accomplish in your life; it's about what you inspire others to do.", author: "Unknown"),
        Quote(text: "Fall seven times and stand up eight.", author: "Japanese Proverb"),
        Quote(text: "Some people dream of success while others wake up and work.", author: "Unknown"),
        Quote(text: "If you can dream it, you can do it.", author: "Walt Disney"),
        Quote(text: "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.", author: "Jordan Belfort"),
        Quote(text: "The only way to achieve the impossible is to believe it is possible.", author: "Charles Kingsleigh"),
        Quote(text: "Don't let yesterday take up too much of today.", author: "Will Rogers"),
        Quote(text: "The future depends on what you do today.", author: "Mahatma Gandhi"),
        Quote(text: "Quality is not an act, it is a habit.", author: "Aristotle"),
        Quote(text: "The best revenge is massive success.", author: "Frank Sinatra"),
        Quote(text: "The difference between ordinary and extraordinary is that little extra.", author: "Jimmy Johnson"),
        Quote(text: "Don't let what you cannot do interfere with what you can do.", author: "John Wooden"),
        Quote(text: "You are braver than you believe, stronger than you seem and smarter than you think.", author: "A.A. Milne"),
        Quote(text: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson"),
        Quote(text: "Go the extra mile. It's never crowded there.", author: "Dr. Wayne D. Dyer"),
        Quote(text: "You don't have to see the whole staircase, just take the first step.", author: "Martin Luther King Jr."),
        Quote(text: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington"),
        Quote(text: "If you can't fly then run, if you can't run then walk, if you can't walk then crawl, but whatever you do you have to keep moving forward.", author: "Martin Luther King Jr."),
        Quote(text: "The best way to get started is to quit talking and begin doing.", author: "Walt Disney"),
        Quote(text: "Don't let the fear of losing be greater than the excitement of winning.", author: "Robert Kiyosaki"),
        Quote(text: "Great minds discuss ideas; average minds discuss events; small minds discuss people.", author: "Eleanor Roosevelt"),
        Quote(text: "If you want to make your dreams come true, the first thing you have to do is wake up.", author: "J.M. Power"),
        Quote(text: "The only thing that overcomes hard luck is hard work.", author: "Harry Golden"),
        Quote(text: "The harder the conflict, the more glorious the triumph.", author: "Thomas Paine"),
        Quote(text: "If you are going through hell, keep going.", author: "Winston Churchill"),
        Quote(text: "The best preparation for tomorrow is doing your best today.", author: "H. Jackson Brown Jr."),
        Quote(text: "Everything you've ever wanted is on the other side of fear.", author: "George Addair"),
        Quote(text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky"),
        Quote(text: "The harder you work for something, the greater you'll feel when you achieve it.", author: "Unknown"),
        Quote(text: "Success doesn't just find you. You have to go out and get it.", author: "Unknown"),
        Quote(text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson"),
        Quote(text: "Don't stop when you're tired. Stop when you're done.", author: "Marilyn Monroe"),
        Quote(text: "It's going to be hard, but hard does not mean impossible.", author: "Unknown"),
        Quote(text: "Don't wait for opportunity. Create it.", author: "George Bernard Shaw"),
        Quote(text: "Sometimes we're tested not to show our weaknesses, but to discover our strengths.", author: "Unknown"),
        Quote(text: "Don't limit your challenges. Challenge your limits.", author: "Jerry Dunn"),
        Quote(text: "Don't be afraid to give up the good to go for the great.", author: "John D. Rockefeller"),
        Quote(text: "Don't be distracted by criticism. Remember—the only taste of success some people get is to take a bite out of you.", author: "Zig Ziglar"),
        Quote(text: "Success isn't just about what you accomplish in your life; it's about what you inspire others to do.", author: "Unknown"),
        Quote(text: "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.", author: "Jordan Belfort"),
        Quote(text: "Don't let yesterday take up too much of today.", author: "Will Rogers"),
        Quote(text: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar"),
        Quote(text: "It always seems impossible until it's done.", author: "Nelson Mandela"),
        Quote(text: "Don't let what you cannot do interfere with what you can do.", author: "John Wooden"),
        Quote(text: "Go the extra mile. It's never crowded there.", author: "Dr. Wayne D. Dyer"),
        Quote(text: "You don't have to see the whole staircase, just take the first step.", author: "Martin Luther King Jr."),
        Quote(text: "If you can't fly then run, if you can't run then walk, if you can't walk then crawl, but whatever you do you have to keep moving forward.", author: "Martin Luther King Jr."),
        Quote(text: "Don't let the fear of losing be greater than the excitement of winning.", author: "Robert Kiyosaki"),
        Quote(text: "The two most important days in your life are the day you are born and the day you find out why.", author: "Mark Twain"),
        Quote(text: "To live is the rarest thing in the world. Most people exist, that is all.", author: "Oscar Wilde"),
        Quote(text: "That it will never come again is what makes life so sweet.", author: "Emily Dickinson"),
        Quote(text: "It is not death that a man should fear, but he should fear never beginning to live.", author: "Marcus Aurelius"),
        Quote(text: "Life is what happens when you're busy making other plans.", author: "John Lennon"),
        Quote(text: "The purpose of our lives is to be happy.", author: "Dalai Lama"),
        Quote(text: "Get busy living or get busy dying.", author: "Stephen King"),
        Quote(text: "You only live once, but if you do it right, once is enough.", author: "Mae West"),
        Quote(text: "Life is really simple, but we insist on making it complicated.", author: "Confucius"),
        Quote(text: "May you live all the days of your life.", author: "Jonathan Swift"),
        Quote(text: "Life itself is the most wonderful fairy tale.", author: "Hans Christian Andersen"),
        Quote(text: "Do not take life too seriously. You will never get out of it alive.", author: "Elbert Hubbard"),
        Quote(text: "To write about life first you must live it.", author: "Ernest Hemingway"),
        Quote(text: "The big lesson in life, baby, is never be scared of anyone or anything.", author: "Frank Sinatra"),
        Quote(text: "In three words I can sum up everything I've learned about life: it goes on.", author: "Robert Frost"),
        Quote(text: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela"),
        Quote(text: "Life is a succession of lessons which must be lived to be understood.", author: "Ralph Waldo Emerson"),
        Quote(text: "The unexamined life is not worth living.", author: "Socrates"),
        Quote(text: "I enjoy life when things are happening. I don't care if it's good things or bad things. That means you're alive.", author: "Joan Rivers"),
        Quote(text: "Life is like riding a bicycle. To keep your balance, you must keep moving.", author: "Albert Einstein"),
        Quote(text: "The minute that you're not learning I believe you're dead.", author: "Jack Nicholson"),
        Quote(text: "Life is a flower of which love is the honey.", author: "Victor Hugo"),
        Quote(text: "Keep smiling, because life is a beautiful thing and there's so much to smile about.", author: "Marilyn Monroe"),
        Quote(text: "Good friends, good books, and a sleepy conscience: this is the ideal life.", author: "Mark Twain"),
        Quote(text: "Life would be tragic if it weren't funny.", author: "Stephen Hawking"),
        Quote(text: "Live in the sunshine, swim the sea, drink the wild air.", author: "Ralph Waldo Emerson"),
        Quote(text: "The most important thing is to enjoy your life—to be happy—it's all that matters.", author: "Audrey Hepburn"),
        Quote(text: "I think being in love with life is a key to eternal youth.", author: "Doug Hutchison"),
        Quote(text: "My mission in life is not merely to survive, but to thrive.", author: "Maya Angelou"),
        Quote(text: "Life is a dream for the wise, a game for the fool, a comedy for the rich, a tragedy for the poor.", author: "Sholom Aleichem"),
        Quote(text: "If life were predictable it would cease to be life, and be without flavor.", author: "Eleanor Roosevelt"),
        Quote(text: "The art of living is more like wrestling than dancing.", author: "Marcus Aurelius"),
        Quote(text: "The trick in life is learning how to deal with it.", author: "Helen Mirren"),
        Quote(text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Aristotle"),
        Quote(text: "The measure of intelligence is the ability to change.", author: "Albert Einstein"),
        Quote(text: "It is the mark of an educated mind to be able to entertain a thought without accepting it.", author: "Aristotle"),
        Quote(text: "A wise man can learn more from a foolish question than a fool can learn from a wise answer.", author: "Bruce Lee"),
        Quote(text: "The journey of a thousand miles begins with a single step.", author: "Lao Tzu"),
        Quote(text: "Knowing yourself is the beginning of all wisdom.", author: "Aristotle"),
        Quote(text: "The only true wisdom is in knowing you know nothing.", author: "Socrates"),
        Quote(text: "Never let your sense of morals get in the way of doing what's right.", author: "Isaac Asimov"),
        Quote(text: "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.", author: "Rumi"),
        Quote(text: "The invariable mark of wisdom is to see the miraculous in the common.", author: "Ralph Waldo Emerson"),
        Quote(text: "The fool doth think he is wise, but the wise man knows himself to be a fool.", author: "William Shakespeare"),
        Quote(text: "Count your age by friends, not years. Count your life by smiles, not tears.", author: "John Lennon"),
        Quote(text: "Any fool can know. The point is to understand.", author: "Albert Einstein"),
        Quote(text: "The simple things are also the most extraordinary things, and only the wise can see them.", author: "Paulo Coelho"),
        Quote(text: "It is better to remain silent at the risk of being thought a fool, than to talk and remove all doubt of it.", author: "Maurice Switzer"),
        Quote(text: "The desire to seem clever often prevents one from being so.", author: "François de La Rochefoucauld"),
        Quote(text: "The saddest aspect of life right now is that science gathers knowledge faster than society gathers wisdom.", author: "Isaac Asimov"),
        Quote(text: "Don't gain the world and lose your soul; wisdom is better than silver or gold.", author: "Bob Marley"),
        Quote(text: "Wisdom is not a product of schooling but of the lifelong attempt to acquire it.", author: "Albert Einstein"),
        Quote(text: "A clever person solves a problem. A wise person avoids it.", author: "Albert Einstein"),
        Quote(text: "It's not what you look at that matters, it's what you see.", author: "Henry David Thoreau"),
        Quote(text: "You will not be punished for your anger, you will be punished by your anger.", author: "Buddha"),
        Quote(text: "The further a society drifts from truth the more it will hate those who speak it.", author: "George Orwell"),
        Quote(text: "The man who asks a question is a fool for a minute, the man who does not ask is a fool for life.", author: "Confucius"),
        Quote(text: "A man is but what he knows.", author: "Francis Bacon"),
        Quote(text: "By three methods we may learn wisdom: First, by reflection, which is noblest; Second, by imitation, which is easiest; and third by experience, which is the bitterest.", author: "Confucius"),
        Quote(text: "Science is organized knowledge. Wisdom is organized life.", author: "Immanuel Kant"),
        Quote(text: "Turn your wounds into wisdom.", author: "Oprah Winfrey"),
        Quote(text: "Wisdom begins in wonder.", author: "Socrates"),
        Quote(text: "He who knows all the answers has not been asked all the questions.", author: "Confucius"),
        Quote(text: "The art of being wise is the art of knowing what to overlook.", author: "William James"),
        Quote(text: "To be uncertain is to be uncomfortable, but to be certain is to be ridiculous.", author: "Chinese Proverb"),
        Quote(text: "Patience is the companion of wisdom.", author: "Saint Augustine"),
        Quote(text: "To conquer fear is the beginning of wisdom.", author: "Bertrand Russell"),
        Quote(text: "Knowledge speaks, but wisdom listens.", author: "Jimi Hendrix"),
        Quote(text: "He who is not a good servant will not be a good master.", author: "Plato"),
        Quote(text: "A single conversation with a wise man is better than ten years of study.", author: "Chinese Proverb"),
        Quote(text: "The doors of wisdom are never shut.", author: "Benjamin Franklin"),
        Quote(text: "We can't solve problems by using the same kind of thinking we used when we created them.", author: "Albert Einstein"),
        Quote(text: "If you're going through hell, keep going.", author: "Winston Churchill"),
        Quote(text: "Strength does not come from physical capacity. It comes from an indomitable will.", author: "Mahatma Gandhi"),
        Quote(text: "It is our choices, Harry, that show what we truly are, far more than our abilities.", author: "J.K. Rowling"),
        Quote(text: "He who has a why to live for can bear almost any how.", author: "Friedrich Nietzsche"),
        Quote(text: "The brick walls are there for a reason. They are not there to keep us out. The brick walls are there to give us a chance to show how badly we want something.", author: "Randy Pausch"),
        Quote(text: "I am not what happened to me, I am what I choose to become.", author: "Carl Jung"),
        Quote(text: "A hero is an ordinary individual who finds the strength to persevere and endure in spite of overwhelming obstacles.", author: "Christopher Reeve"),
        Quote(text: "It's not the load that breaks you down, it's the way you carry it.", author: "Lou Holtz"),
        Quote(text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson"),
        Quote(text: "Perseverance is not a long race; it is many short races one after the other.", author: "Walter Elliot"),
        Quote(text: "The world breaks everyone, and afterward, some are strong at the broken places.", author: "Ernest Hemingway"),
        Quote(text: "Do not pray for an easy life, pray for the strength to endure a difficult one.", author: "Bruce Lee"),
        Quote(text: "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will.", author: "Vince Lombardi"),
        Quote(text: "You have power over your mind - not outside events. Realize this, and you will find strength.", author: "Marcus Aurelius"),
        Quote(text: "Courage is resistance to fear, mastery of fear - not absence of fear.", author: "Mark Twain"),
        Quote(text: "It is not the mountain we conquer, but ourselves.", author: "Sir Edmund Hillary"),
        Quote(text: "Tough times never last, but tough people do.", author: "Robert H. Schuller"),
        Quote(text: "I can be changed by what happens to me. But I refuse to be reduced by it.", author: "Maya Angelou"),
        Quote(text: "A truly strong person does not need the approval of others any more than a lion needs the approval of sheep.", author: "Vernon Howard"),
        Quote(text: "When a defining moment comes along, you can do one of two things. Define the moment, or let the moment define you.", author: "Roy McAvoy"),
        Quote(text: "Fall down seven times, stand up eight.", author: "Japanese Proverb"),
        Quote(text: "When you have exhausted all possibilities, remember this: you haven't.", author: "Thomas A. Edison"),
        Quote(text: "Character cannot be developed in ease and quiet. Only through experience of trial and suffering can the soul be strengthened, ambition inspired, and success achieved.", author: "Helen Keller"),
        Quote(text: "When you come to the end of your rope, tie a knot and hang on.", author: "Franklin D. Roosevelt"),
        Quote(text: "The human spirit is stronger than anything that can happen to it.", author: "C.C. Scott"),
        Quote(text: "We must embrace pain and burn it as fuel for our journey.", author: "Kenji Miyazawa"),
        Quote(text: "The gem cannot be polished without friction, nor man perfected without trials.", author: "Chinese Proverb"),
        Quote(text: "I ask not for a lighter burden, but for broader shoulders.", author: "Jewish Proverb"),
        Quote(text: "What the caterpillar calls the end of the world, the master calls a butterfly.", author: "Richard Bach"),
        Quote(text: "In the middle of difficulty lies opportunity.", author: "Albert Einstein"),
        Quote(text: "If you are distressed by anything external, the pain is not due to the thing itself, but to your estimate of it; and this you have the power to revoke at any moment.", author: "Marcus Aurelius"),
        Quote(text: "You may have to fight a battle more than once to win it.", author: "Margaret Thatcher"),
        Quote(text: "A smooth sea never made a skilled sailor.", author: "Franklin D. Roosevelt"),
        Quote(text: "Never give in. Never give in. Never, never, never, never—in nothing, great or small, large or petty—never give in, except to convictions of honour and good sense.", author: "Winston Churchill"),
        Quote(text: "Show me someone who has done something worthwhile, and I'll show you someone who has overcome adversity.", author: "Lou Holtz"),
        Quote(text: "We must be willing to let go of the life we have planned, so as to have the life that is waiting for us.", author: "Joseph Campbell"),
        Quote(text: "Start by doing what's necessary; then do what's possible; and suddenly you are doing the impossible.", author: "Francis of Assisi"),
        Quote(text: "The first step toward success is taken when you refuse to be a captive of the environment in which you first find yourself.", author: "Mark Caine"),
        Quote(text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt"),
        Quote(text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt"),
        Quote(text: "I am looking for a lot of men who have an infinite capacity to not know what can't be done.", author: "Henry Ford"),
        Quote(text: "If you have the courage to begin, you have the courage to succeed.", author: "David Viscott"),
        Quote(text: "I would rather die of passion than of boredom.", author: "Vincent van Gogh"),
        Quote(text: "The undertaking of a new action brings new strength.", author: "Richard L. Evans"),
        Quote(text: "A man is not finished when he is defeated. He is finished when he quits.", author: "Richard Nixon"),
        Quote(text: "If you don't like something, change it. If you can't change it, change your attitude.", author: "Maya Angelou"),
        Quote(text: "When everything seems to be going against you, remember that the airplane takes off against the wind, not with it.", author: "Henry Ford"),
        Quote(text: "Too many of us are not living our dreams because we are living our fears.", author: "Les Brown"),
        Quote(text: "I am always doing that which I cannot do, in order that I may learn how to do it.", author: "Pablo Picasso"),
        Quote(text: "Build your own dreams, or someone else will hire you to build theirs.", author: "Farrah Gray"),
        Quote(text: "The most effective way to do it, is to do it.", author: "Amelia Earhart"),
        Quote(text: "A person who never made a mistake never tried anything new.", author: "Albert Einstein"),
        Quote(text: "The best revenge is massive success.", author: "Frank Sinatra"),
        Quote(text: "I have not failed. I've just found 10,000 ways that won't work.", author: "Thomas A. Edison"),
        Quote(text: "Success is the sum of small efforts, repeated day-in and day-out.", author: "Robert Collier"),
        Quote(text: "If you want to achieve excellence, you can get there today. As of this second, quit doing less-than-excellent work.", author: "Thomas J. Watson"),
        Quote(text: "What you do today can improve all your tomorrows.", author: "Ralph Marston"),
        Quote(text: "The secret of change is to focus all of your energy, not on fighting the old, but on building the new.", author: "Socrates"),
        Quote(text: "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.", author: "Roy T. Bennett"),
        Quote(text: "Instead of worrying about what you cannot control, shift your energy to what you can create.", author: "Roy T. Bennett"),
        Quote(text: "I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.", author: "Maya Angelou"),
        Quote(text: "Whether you think you can or you think you can't, you're right.", author: "Henry Ford"),
        Quote(text: "Creativity is intelligence having fun.", author: "Albert Einstein"),
        Quote(text: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Zig Ziglar"),
        Quote(text: "The mind is its own place, and in itself can make a heaven of hell, a hell of heaven.", author: "John Milton"),
        Quote(text: "A year from now you may wish you had started today.", author: "Karen Lamb"),
        Quote(text: "Someday is not a day of the week.", author: "Janet Dailey"),
        Quote(text: "Don't wait. The time will never be just right.", author: "Napoleon Hill"),
        Quote(text: "Amateurs sit and wait for inspiration, the rest of us just get up and go to work.", author: "Stephen King"),
        Quote(text: "If you hear a voice within you say 'you cannot paint,' then by all means paint, and that voice will be silenced.", author: "Vincent Van Gogh"),
        Quote(text: "The question isn't who is going to let me; it's who is going to stop me.", author: "Ayn Rand"),
        Quote(text: "Don't let the perfect be the enemy of the good.", author: "Voltaire"),
        Quote(text: "You can't use up creativity. The more you use, the more you have.", author: "Maya Angelou"),
        Quote(text: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson"),
        Quote(text: "If you are not willing to risk the usual, you will have to settle for the ordinary.", author: "Jim Rohn"),
        Quote(text: "Talent is cheaper than table salt. What separates the talented individual from the successful one is a lot of hard work.", author: "Stephen King"),
        Quote(text: "The artist is nothing without the gift, but the gift is nothing without work.", author: "Émile Zola"),
        Quote(text: "Genius is one percent inspiration and ninety-nine percent perspiration.", author: "Thomas Edison"),
        Quote(text: "A goal is a dream with a deadline.", author: "Napoleon Hill"),
        Quote(text: "The best way to appreciate your job is to imagine yourself without one.", author: "Oscar Wilde"),
        Quote(text: "Choose a job you love, and you will never have to work a day in your life.", author: "Confucius"),
        Quote(text: "The only place where success comes before work is in the dictionary.", author: "Vidal Sassoon"),
        Quote(text: "The expert in anything was once a beginner.", author: "Helen Hayes"),
        Quote(text: "Concentrate all your thoughts upon the work in hand. The sun's rays do not burn until brought to a focus.", author: "Alexander Graham Bell"),
        Quote(text: "The man who moves a mountain begins by carrying away small stones.", author: "Confucius"),
        Quote(text: "Don't count the days, make the days count.", author: "Muhammad Ali"),
        Quote(text: "I'm a greater believer in luck, and I find the harder I work the more I have of it.", author: "Thomas Jefferson"),
        Quote(text: "When we strive to become better than we are, everything around us becomes better too.", author: "Paulo Coelho"),
        Quote(text: "Opportunity is missed by most people because it is dressed in overalls and looks like work.", author: "Thomas Edison"),
        Quote(text: "You've got to get up every morning with determination if you're going to go to bed with satisfaction.", author: "George Lorimer"),
        Quote(text: "Pleasure in the job puts perfection in the work.", author: "Aristotle"),
        Quote(text: "Just one small positive thought in the morning can change your whole day.", author: "Dalai Lama"),
        Quote(text: "The future of work is not about degrees, it's about skills.", author: "Unknown"),
        Quote(text: "The journey of a thousand miles begins with a single step.", author: "Lao Tzu"),
        Quote(text: "If you want to live a happy life, tie it to a goal, not to people or things.", author: "Albert Einstein"),
        Quote(text: "Your time is limited, so don't waste it living someone else's life.", author: "Steve Jobs"),
        Quote(text: "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well.", author: "Ralph Waldo Emerson"),
        Quote(text: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", author: "Ralph Waldo Emerson"),
        Quote(text: "Two roads diverged in a wood, and I—I took the one less traveled by, And that has made all the difference.", author: "Robert Frost"),
        Quote(text: "The only thing we have to fear is fear itself.", author: "Franklin D. Roosevelt"),
        Quote(text: "The mind is everything. What you think you become.", author: "Buddha"),
        Quote(text: "An unexamined life is not worth living.", author: "Socrates"),
        Quote(text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb"),
        Quote(text: "It is never too late to be what you might have been.", author: "George Eliot"),
        Quote(text: "A day without laughter is a day wasted.", author: "Charlie Chaplin"),
        Quote(text: "You must be the change you wish to see in the world.", author: "Mahatma Gandhi"),
        Quote(text: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein"),
        Quote(text: "I have learned over the years that when one's mind is made up, this diminishes fear.", author: "Rosa Parks"),
        Quote(text: "The power of imagination makes us infinite.", author: "John Muir"),
        Quote(text: "Logic will get you from A to B. Imagination will take you everywhere.", author: "Albert Einstein"),
        Quote(text: "Everything you can imagine is real.", author: "Pablo Picasso"),
        Quote(text: "Imagination is the beginning of creation. You imagine what you desire, you will what you imagine and at last you create what you will.", author: "George Bernard Shaw"),
        Quote(text: "Imagination is more important than knowledge. Knowledge is limited. Imagination encircles the world.", author: "Albert Einstein"),
        Quote(text: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt"),
        Quote(text: "You can't depend on your eyes when your imagination is out of focus.", author: "Mark Twain"),
        Quote(text: "Laughter is timeless, imagination has no age, and dreams are forever.", author: "Walt Disney"),
        Quote(text: "The world is but a canvas to our imagination.", author: "Henry David Thoreau"),
        Quote(text: "True imagination is not fanciful, but practical. It is the power to see what is not, but could be.", author: "Charles F. Haanel"),
        Quote(text: "Without imagination, nothing is dangerous.", author: "John Cage"),
        Quote(text: "Imagination creates reality.", author: "Richard Wagner"),
        Quote(text: "Imagination is the eye of the soul.", author: "Joseph Joubert"),
        Quote(text: "What is now proved was once only imagined.", author: "William Blake"),
        Quote(text: "Limitations live only in our minds. But if we use our imaginations, our possibilities become limitless.", author: "Jamie Paolinetti"),
        Quote(text: "Imagination is a weapon. Those who don't use it are unarmed.", author: "T. B. Joshua"),
        Quote(text: "Imagination will often carry us to worlds that never were, but without it we go nowhere.", author: "Carl Sagan"),
        Quote(text: "The man who has no imagination has no wings.", author: "Muhammad Ali"),
        Quote(text: "Imagination is the highest kite one can fly.", author: "Lauren Bacall"),
        Quote(text: "Imagination does not become great until human beings, given the courage and the strength, use it to create.", author: "Maya Angelou"),
        Quote(text: "Our imagination is the only limit to what we can hope to have in the future.", author: "Charles F. Kettering"),
        Quote(text: "The true sign of intelligence is not knowledge but imagination.", author: "Albert Einstein"),
        Quote(text: "Worry is a misuse of imagination.", author: "Dan Zadra"),
        Quote(text: "Crying is for plain women. Pretty women go shopping.", author: "Oscar Wilde"),
        Quote(text: "The future is something which everyone reaches at the rate of sixty minutes an hour, whatever he does, whoever he is.", author: "C.S. Lewis"),
        Quote(text: "Man is a mystery. It needs to be unravelled, and if you spend your whole life unravelling it, don't say that you've wasted time. I am studying that mystery because I want to be a human being.", author: "Fyodor Dostoevsky"),
        Quote(text: "A creative man is motivated by the desire to achieve, not by the desire to beat others.", author: "Ayn Rand"),
        Quote(text: "Talent hits a target no one else can hit. Genius hits a target no one else can see.", author: "Arthur Schopenhauer"),
        Quote(text: "There is nothing to writing. All you do is sit down at a typewriter and bleed.", author: "Ernest Hemingway"),
        Quote(text: "I write to discover what I know.", author: "Flannery O'Connor"),
        Quote(text: "If there's a book that you want to read, but it hasn't been written yet, then you must write it.", author: "Toni Morrison"),
        Quote(text: "A writer is someone for whom writing is more difficult than it is for other people.", author: "Thomas Mann"),
        Quote(text: "A professional writer is an amateur who didn't quit.", author: "Richard Bach"),
        Quote(text: "Start writing, no matter what. The water does not flow until the faucet is turned on.", author: "Louis L'Amour"),
        Quote(text: "Every secret of a writer's soul, every experience of his life, every quality of his mind, is written large in his works.", author: "Virginia Woolf"),
        Quote(text: "And by the way, everything in life is writable about if you have the outgoing guts to do it, and the imagination to improvise. The worst enemy to creativity is self-doubt.", author: "Sylvia Plath"),
        Quote(text: "The purpose of a writer is not to say what we all can say, but what we are unable to say.", author: "Anaïs Nin"),
        Quote(text: "Words are our most inexhaustible source of magic.", author: "J.K. Rowling"),
        Quote(text: "All you have to do is write one true sentence. Write the truest sentence that you know.", author: "Ernest Hemingway"),
        Quote(text: "I write for the same reason I breathe - because if I didn't, I would die.", author: "Isaac Asimov"),
        Quote(text: "Read a thousand books, and your words will flow like a river.", author: "Lisa See"),
        Quote(text: "You can't wait for inspiration. You have to go after it with a club.", author: "Jack London"),
        Quote(text: "There is no rule on how to write. Sometimes it comes easily and perfectly; sometimes it's like drilling rock and then blasting it out with charges.", author: "Ernest Hemingway")
    ]

    static func randomQuote() -> Quote {
        return quotes.randomElement() ?? Quote(text: "Every moment is a fresh beginning.", author: "T.S. Eliot")
    }
}
